apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: opsconfigs.ops.openshift.com
spec:
  group: ops.openshift.com
  names:
    kind: Opsconfig
    listKind: OpsconfigList
    plural: opsconfigs
    singular: opsconfig
  scope: Namespaced
  version: v1alpha1
