apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: opsconfigs.ops.openshift.com
spec:
  group: ops.openshift.com
  names:
    kind: Opsconfig
    listKind: OpsconfigList
    plural: opsconfigs
    singular: opsconfig
  scope: Namespaced
  version: v1alpha1

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opsconfig-operator
  namespace: opsconfig

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: opsconfig-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - ops.openshift.com
  resources:
  - '*'
  verbs:
  - '*'

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: opsconfig-operator
subjects:
- kind: ServiceAccount
  name: opsconfig-operator
  namespace: opsconfig
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
